name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        os: ['windows-latest', 'ubuntu-latest']
        include:
          - os: 'windows-latest'
            test-dir: 'tools/test/data/windows'
          - os: 'ubuntu-latest'
            test-dir: 'tools/test/data/linux'

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r tools/requirements.txt
    - name: Unittest
      run: python -m unittest discover tools/test
    - name: Build whl
      run: |
        python -m pip install build
        python -m build
    - name: Install whl
      run: python -m pip install dist/*.whl
    - name: Test whl
      run: |
        cd ${{ matrix.test-dir }}
        hatlib.hat_to_dynamic optimized_matmul.hat optimized_matmul.dll.hat
        hatlib.benchmark_hat optimized_matmul.dll.hat
